FROM python:3.8.3-slim

WORKDIR /usr/src/my_app

COPY user_interface/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY user_interface .

EXPOSE 8000

CMD ["/usr/src/my_app/manage.py", "runserver", "0.0.0.0:8000"]